[2024-04-03T21:27:11.650+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB-DAG.download-dataset-tasks.download_title.principals_task manual__2024-04-03T21:27:08.352096+00:00 [queued]>
[2024-04-03T21:27:11.692+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB-DAG.download-dataset-tasks.download_title.principals_task manual__2024-04-03T21:27:08.352096+00:00 [queued]>
[2024-04-03T21:27:11.695+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-03T21:27:11.731+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download-dataset-tasks.download_title.principals_task> on 2024-04-03 21:27:08.352096+00:00
[2024-04-03T21:27:11.746+0000] {standard_task_runner.py:60} INFO - Started process 3707 to run task
[2024-04-03T21:27:11.765+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'IMDB-DAG', 'download-dataset-tasks.download_title.principals_task', 'manual__2024-04-03T21:27:08.352096+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/imdb_dab.py', '--cfg-path', '/tmp/tmpyig85asw']
[2024-04-03T21:27:11.769+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask download-dataset-tasks.download_title.principals_task
[2024-04-03T21:27:11.886+0000] {task_command.py:423} INFO - Running <TaskInstance: IMDB-DAG.download-dataset-tasks.download_title.principals_task manual__2024-04-03T21:27:08.352096+00:00 [running]> on host 092193d62c58
[2024-04-03T21:27:12.089+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='IMDB-DAG' AIRFLOW_CTX_TASK_ID='download-dataset-tasks.download_title.principals_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T21:27:08.352096+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T21:27:08.352096+00:00'
[2024-04-03T21:27:12.097+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-03T21:27:12.101+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -o /opt/***/raws/title.principals.tsv.gz -p https://datasets.imdbws.com/title.principals.tsv.gz']
[2024-04-03T21:27:12.129+0000] {subprocess.py:86} INFO - Output:
[2024-04-03T21:27:12.195+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-04-03T21:27:12.205+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-04-03T21:27:12.419+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file /opt/***/raws/title.principals.tsv.gz: No
[2024-04-03T21:27:12.432+0000] {subprocess.py:93} INFO - Warning: such file or directory
[2024-04-03T21:27:12.433+0000] {subprocess.py:93} INFO -   0  627M    0 16015    0     0  71051      0  2:34:25 --:--:--  2:34:25 71177
[2024-04-03T21:27:12.434+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-04-03T21:27:12.440+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-04-03T21:27:12.474+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-04-03T21:27:12.485+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=IMDB-DAG, task_id=download-dataset-tasks.download_title.principals_task, execution_date=20240403T212708, start_date=20240403T212711, end_date=20240403T212712
[2024-04-03T21:27:12.508+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task download-dataset-tasks.download_title.principals_task (Bash command failed. The command returned a non-zero exit code 23.; 3707)
[2024-04-03T21:27:12.540+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T21:27:12.616+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
